routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::group([
    'prefix' => LaravelLocalization::setLocale(),
    'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath']
], function () {
    Route::get('/', 'HomeController@index');

    //Book routes
    Route::resource('book', 'BookController');

    //User books
    Route::get('/my-library', 'BookController@userLibrary');

    //Users routes
    Route::resource('user', 'UserController');

    Auth::routes();

    Route::get('login', [
        'as' => 'login',
        'uses' => 'Auth\LoginController@showLoginForm'
    ]);

    Route::post('login', [
        'as' => '',
        'uses' => 'Auth\LoginController@login'
    ]);
    Route::post('logout', [
        'as' => 'logout',
        'uses' => 'Auth\LoginController@logout'
    ]);

    Route::post('/available/{id}', 'BookController@available');
});

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Book extends Model
{
    use SoftDeletes;

    /**
     * @var array
     */
    protected $guarded = ['_token', 'user_id'];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at', 'taken_at'];

    /**
     * return object
     */
    public function user()
    {
        return $this->hasOne(UserBook::class);
    }

    /**
     * @param $query
     * @param $filters
     */
    public function scopeFilter($query, $filters)
    {
        if ($keyword = $filters['search']) {
            $query->where("name", "LIKE", "%$keyword%")
                ->orWhere("author", "LIKE", "%$keyword%")
                ->orWhere("signature", "LIKE", "%$keyword%");
        }

        if ($filter = $filters['filter']) {
            if ($filter == "available")
                $query->where('available', 1);
            else
                $query->where('available', 0);
        }

        if ($order = $filters['order']) {
            $query->orderBy('created_at', $order);
        } else {
            $query->orderBy('created_at', 'desc');
        }
    }
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use App\Book;
use App\Http\Requests\BookRequest;
use Illuminate\Http\Request;
use App\User;
use App\UserBook;

class BookController extends Controller
{
    /**
     * @var Book
     */
    protected $oBook;

    /**
     * BookController constructor.
     * @param Book $oBook
     */
    public function __construct(Book $oBook)
    {
        $this->middleware('auth');
        $this->middleware('admin')->except('userLibrary');
        $this->middleware('user')->only('userLibrary');

        $this->oBook = $oBook;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $oBooks = $this->oBook
            ->filter(request()->all(['search', 'filter', 'order']))
            ->paginate(10);

        return view('book.index', compact('oBooks'));
    }

    /**
     * 
     * @return \Illuminate\Http\Response
     */
    public function userLibrary() {

        $oUserBooks = auth()->user()->book()
            ->filter(request()->all(['search', 'filter', 'order']))
            ->paginate(10);

        return view('user.library.index', compact('oUserBooks'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(request()->has('copy')) {
            $oBook = $this->oBook->findOrFail(request('copy'));
        }

        $oUsers = auth()->user()->userRole()->get(['id', 'name']);

        return view('book.create', [
            'oBook' => isset($oBook) ? $oBook : [],
            'oUsers' => $oUsers
        ]);
    }

    /**
     * @param BookRequest $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(BookRequest $request)
    {
        $data = $request->all();
        $data['taken_at'] = !request('available') ? date('Y-m-d H:i:s') : null;

        $oBook = $this->oBook->create($data);

        if(!request('available')) {
            $oBook->user()->updateOrCreate(
                ['book_id' => $oBook->id, 'deleted_at'   => null],
                ['user_id' => request('user_id')
            ]);
        } else {
            $oUserBook = UserBook::where(['book_id' => $oBook->id, 'deleted_at' => null])->first();
            if($oUserBook) {
                $oUserBook->deleted_at = date('Y-m-d H:m:s');
                $oUserBook->save();
            }
        }

        $request->session()->flash('message', __('Successfully created book with name'). ' ' . $oBook->name . '.');
        return redirect('/book');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function show(Book $book)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function edit(Book $book)
    {
        $oUsers = auth()->user()->userRole()->get(['id', 'name']);

        return view('book.edit', ['oBook' => $book, 'oUsers' => $oUsers]);
    }

    /**
     * @param BookRequest $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(BookRequest $request, $id)
    {
        $data = $request->all();
        $data['taken_at'] = !request('available') ? date('Y-m-d H:i:s') : null;

        $oBook = $this->oBook->find($id);
        $oBook->update($data);
        
        if(!request('available')) {
            $oBook->user()->updateOrCreate(
                ['book_id' => $id, 'deleted_at' => null],
                ['user_id' => request('user_id')
            ]);
        } else {
            $oUserBook = UserBook::where(['book_id' => $id, 'deleted_at' => null])->first();
            if($oUserBook) {
                $oUserBook->deleted_at = date('Y-m-d H:m:s');
                $oUserBook->save();
            }
        }

        $request->session()->flash('message', __('Successfully edited book with name') . ' ' . $oBook->name . '.');
        return redirect('/book');
    }

    /** 
     * @param Request $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy(Request $request, $id)
    {
        $this->oBook->destroy($id);

        $request->session()->flash('message', __('Successfully deleted book') . '.');
        return redirect('/book');
    }

    /**
     * @param int $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function available($id)
    {
        if (request()->ajax()) {
            try {
                $oBook = $this->oBook->findOrFail($id);
                $oBook->update([
                    'available' => request('available'),
                    'taken_at' => !request('available') ? date('Y-m-d H:i:s') : null,
                ]);

                return response()->json([
                    'success' => $oBook,
                    'message' => __('Successfully edited book with name') . ' '
                ]);
            } catch (\Exception $e) {
                return response()->json([
                    'error' => $e->getMessage(),    
                    'message' => __('Something went wrong') . '.'
                ], 404);
            }
        }
    }
}

resources/views/book/create.blade.php
@extends('layouts.app')

@section('content')

    <h2>{{ request()->has('copy') ? __('Copy a book') : __('Create a book') }}</h2>

    <form action="{{ route('book.store') }}" method="post">
        {{ csrf_field() }}  

        <div class="form-group required {{ $errors->has('name') ? 'has-error': '' }}">
            <label class="control-label" for="name">{{ __('Name') }}</label>
            <input id="name" type="text" name="name" class='form-control' value="{{ !empty($oBook) ? $oBook->name : old('name') }}">
            <div class="help-block">{{ $errors->first('name') }}</div>
        </div>

        <div class="form-group required {{ $errors->has('author') ? 'has-error': '' }}">
            <label class="control-label" for="author">{{ __('Author') }}</label>
            <input id="author" type="text" name="author" class='form-control' value="{{ !empty($oBook) ? $oBook->author : old('author') }}">
            <div class="help-block">{{ $errors->first('author') }}</div>
        </div>

        <div class="form-group required {{ $errors->has('signature') ? 'has-error': '' }}">
            <label class="control-label" for="signature">{{ __('Signature') }}</label>
            <input id="signature" type="text" name="signature" class='form-control' value="{{ !empty($oBook) ? $oBook->signature : old('signature') }}">
            <div class="help-block">{{ $errors->first('signature') }}</div>
        </div>

        <div class="form-group required {{ $errors->has('section') ? 'has-error': '' }}">
            <label class="control-label" for="section">{{ __('Section') }}</label>
            <input id="section" type="text" name="section" class='form-control' value="{{ !empty($oBook) ? $oBook->section : old('section') }}">
            <div class="help-block">{{ $errors->first('section') }}</div>
        </div>

        <div class="form-group required {{ $errors->has('number') ? 'has-error': '' }}">
            <label class="control-label"  for="number">{{ __('Number') }}</label>
            <input id="number" type="text" name="number" class='form-control' value="{{ !empty($oBook) ? $oBook->number : old('number') }}">
            <div class="help-block">{{ $errors->first('number') }}</div>
        </div>

        <div class="form-group">
            <label>{{ __('Available') }}</label>
            <div class="form">
                <div class="btn-group" data-toggle="buttons">
                    <input type='hidden' value='0' name='available'>
                    <input type="checkbox" {{ $errors->first('user_id') ? '' : 'checked'  }} name="available" data-toggle="toggle" value="1"
                    data-on="{{ __('Yes') }}" data-off="{{ __('No') }}" data-onstyle="success" data-offstyle="danger">
                </div>
            </div>
        </div>

        @if($oUsers->count())
            <div class="form-group book-user {{ $errors->first('user_id') ? '' : 'hidden'  }} ui-widget {{ $errors->has('user_id') ? 'has-error': '' }}">
                <label class="control-label"  for="users">{{ __('Users') }}</label>
                <select class="form-control" id="users" name="user_id">
                    <option value=""></option>
                    @foreach ($oUsers as $oUser)
                        <option value="{{ $oUser->id }}">{{ $oUser->name }}</option>
                    @endforeach
                </select>   
                <div class="help-block">{{ $errors->first('user_id') }}</div>
            </div>
        @endif

        <input type="submit" class='btn btn-primary' value="{{ __('Save') }}">
        <a href="{{ URL::previous() }}" class='btn btn-default'>{{ __('Back') }}</a>

    </form>
    &nbsp

@endsection

resources/views/book/edit.blade.php
@extends('layouts.app')

@section('content')

    <h2>{{ __('Update a book') }}</h2>

    <form action="{{ route('book.update', $oBook->id) }}" method="post">
        <input name="_method" type="hidden" value="PUT">
        {{ csrf_field() }}

        <div class="form-group required {{ $errors->has('name') ? 'has-error': '' }}">
            <label class="control-label" for="name">{{ __('Name') }}</label>
            <input id="name" type="text" name="name" class='form-control' value="{{ isset($oBook) ? $oBook->name : old('name') }}">
            <div class="help-block">{{ $errors->first('name') }}</div>
        </div>

        <div class="form-group required {{ $errors->has('author') ? 'has-error': '' }}">
            <label class="control-label" for="author">{{ __('Author') }}</label>
            <input id="author" type="text" name="author" class='form-control' value="{{ isset($oBook) ? $oBook->author : old('author') }}">
            <div class="help-block">{{ $errors->first('author') }}</div>
        </div>

        <div class="form-group required {{ $errors->has('signature') ? 'has-error': '' }}">
            <label class="control-label" for="signature">{{ __('Signature') }}</label>
            <input id="signature" type="text" name="signature" class='form-control' value="{{ isset($oBook) ? $oBook->signature : old('signature') }}">
            <div class="help-block">{{ $errors->first('signature') }}</div>
        </div>

        <div class="form-group required {{ $errors->has('section') ? 'has-error': '' }}">
            <label class="control-label" for="section">{{ __('Section') }}</label>
            <input id="section" type="text" name="section" class='form-control' value="{{ isset($oBook) ? $oBook->section : old('section') }}">
            <div class="help-block">{{ $errors->first('section') }}</div>
        </div>

        <div class="form-group required {{ $errors->has('number') ? 'has-error': '' }}">
            <label class="control-label"  for="number">{{ __('Number') }}</label>
            <input id="number" type="text" name="number" class='form-control' value="{{ isset($oBook) ? $oBook->number : old('number') }}">
            <div class="help-block">{{ $errors->first('number') }}</div>
        </div>

        <div class="form-group">
            <label>{{ __('Available') }}</label>
            <div class="form">
                <div class="btn-group" data-toggle="buttons">
                    <div class="btn-group" data-toggle="buttons">
                        <input type='hidden' value='0' name='available'>
                        <input type="checkbox" name="available" {{ $oBook->available ? 'checked' : '' }} 
                        data-toggle="toggle" 
                        data-on="{{ __('Yes') }}" data-off="{{ __('No') }}" data-onstyle="success" data-offstyle="danger" value="1">
                    </div>
                </div>
            </div>
        </div>

        @if($oUsers->count())
            <div class="form-group book-user {{ $oBook->available ? 'hidden' : '' }}  {{ $errors->has('user_id') ? 'has-error': '' }}">
                <label class="control-label"  for="user_id">{{ __('Users') }}</label>
                <select class="form-control" id="users" name="user_id">
                    <option value=""></option>
                    @foreach ($oUsers as $oUser)
                        <option {{ $oBook->user && $oBook->user->user_id == $oUser->id ? 'selected' : '' }} value="{{ $oUser->id }}">{{ $oUser->name }}</option>
                    @endforeach
                </select>
                <div class="help-block">{{ $errors->first('user_id') }}</div>
            </div>
        @endif

        <input type="submit" class='btn btn-primary' value="{{ __('Save') }}">
        <a href="{{ URL::previous() }}" class='btn btn-default'>{{ __('Back') }}</a>

    </form>
    &nbsp

@endsection

resources/views/book/index.blade.php
@extends('layouts.app')

@section('content')

    @include('layouts.message')

    <h3>{{ __('Library books') }}</h3>

    <a href="/book/create" class="btn btn-default" style="margin-bottom:15px;">
        <span class="glyphicon glyphicon-plus"></span>
        {{ __('Create a book') }}
    </a>
    
    <div class="row text-center">
        <form action="{{ url('/book') }}" method="get">
            <div class="col-md-5 form-group">
                <div class="input-group col-md-12">
                    <input type="text" name="search" value="{{ request('search') }}" class="form-control" placeholder="{{ __('Search by name') }}"/>
                    <input type="hidden" name="order" value="{{ request('order') }}"/>
                    <input type="hidden" name="filter" value="{{ request('filter') }}"/>
                    <span class="input-group-btn">
                        <button class="btn btn-primary" type="submit">
                            {{ __('Search') }}
                        </button>
                    </span>
                </div>
            </div>
        </form>
        @include('layouts.search', ['filter' => ['available', 'unavailable']])
        
    </div>

    @if(count($oBooks))

        <div class="table-responsive">
            <table class="table" data-form="deleteForm">
                <thead class="thead-inverse">
                <tr>
                    <th width="20%">{{ __('Name') }}</th>
                    <th width="15%">{{ __('Author') }}</th>
                    <th>{{ __('Signature') }}</th>
                    <th>{{ __('Section') }}</th>
                    <th>{{ __('Number') }}</th>
                    <th>{{ __('Return date') }}</th>
                    {{-- <th>{{ __('Added') }}</th> --}}
                    <th>{{ __('Available') }}</th>
                    <th>{{ __('Action') }}</th>
                </tr>
                </thead>
                <tbody>
                @foreach($oBooks as $oBook)
                    <tr>
                        <td>{{ isset($oBook->name) ? str_limit($oBook->name, 20, '...') : '' }}</td>
                        <td>{{ isset($oBook->author) ? str_limit($oBook->author, 20, '...' ): '' }}</td>
                        <td>{{ isset($oBook->author) ? str_limit($oBook->signature, 10, '...' ): '' }}</td>
                        <td>{{ isset($oBook->author) ? str_limit($oBook->section, 10, '...' ): '' }}</td>
                        <td>{{ isset($oBook->number) ? $oBook->number : '' }}</td>
                        <td class='taken-date'>{{ isset($oBook->taken_at) ? ($oBook->taken_at->modify('+30 day'))->format('d-m-Y') : 'N/A' }}</td>
                        <td>
                            <div class="form-group">
                                <div class="form">
                                    <div class="btn-group" data-toggle="buttons">
                                        <input type="checkbox" id="toggle-event" name="available" class="available" {{ $oBook->available ? 'checked' : '' }} data-toggle="toggle" 
                                        data-on="{{ __('Yes') }}" data-off="{{ __('No') }}" data-onstyle="success" data-offstyle="danger" data-style="testtoggle">
                                    </div>
                                </div>
                            </div>
                        </td>
                        
                        <td>
                            <div style="width:max-content;">     
                                <a href="/book/{{$oBook->id}}/edit" class="btn btn-primary pull-left form-group" style="margin-right: 5px;">
                                    <span class="glyphicon glyphicon-pencil"></span>
                                </a>
                                
                                <a href="/book/create?copy={{ $oBook->id }}" class="btn btn-info pull-left form-group" style="margin-right: 5px;">
                                    <span class="glyphicon glyphicon-copy"></span>
                                </a>

                                {{ Form::model($oBook, ['method' => 'delete', 'route' => ['book.destroy', $oBook->id], 'class' => 'pull-right form-delete']) }}
                                {{ Form::hidden('id', $oBook->id) }}
                                {{ Form::button('<span class="glyphicon glyphicon-remove"></span>', ['type' => 'submit', 'class' => 'btn btn-danger'] )  }}
                                {{ Form::close() }}

                            </div>
                        </td>

                        <input type="hidden" name="bookId" value="{{ $oBook->id }}">
                    </tr>
                @endforeach
                </tbody>
            </table>

            @include('modals.delete-modal')
        </div>

        {{ $oBooks->appends(['order' => request('order'), 'filter' => request('filter')])->links() }}

    @else

        <div class="alert alert-warning">
            {{ __('No books found') }}.
        </div>

    @endif
@endsection