routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::group([
    'prefix' => LaravelLocalization::setLocale(),
    'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath']
], function () {
    Route::get('/', 'HomeController@index');

    //Book routes
    Route::resource('book', 'BookController');

    //User books
    Route::get('/my-library', 'BookController@userLibrary');

    //Users routes
    Route::resource('user', 'UserController');

    Auth::routes();

    Route::get('login', [
        'as' => 'login',
        'uses' => 'Auth\LoginController@showLoginForm'
    ]);

    Route::post('login', [
        'as' => '',
        'uses' => 'Auth\LoginController@login'
    ]);
    Route::post('logout', [
        'as' => 'logout',
        'uses' => 'Auth\LoginController@logout'
    ]);

    Route::post('/available/{id}', 'BookController@available');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Authenticatable
{
    use Notifiable;
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'last_name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];

    /**
     * return object
     */
    public function role()
    {
        return $this->hasOne(UserRole::class);
    }

    /**
     * return object
     */
    public function book()
    {
        return $this->hasMany(UserBook::class);
    }

    /**
     * return user type
     */
    public function isAdmin()
    {
        return $this->role->role_id == 1;
    }

    /**
     * @param UserRole $role
     * @param int      $id
     */
    public function saveUserRole(UserRole $role, $id)
    {
        $role->timestamps = false;
        $role->role_id = $id;

        $this->role()->save($role);
    }

    /**
     * @param $query
     * @param $filters
     */
    public function scopeFilter($query, $filters)
    {
        if ($keyword = $filters['search']) {
            $query->where("name", "LIKE", "%$keyword%")
                ->orWhere("email", "LIKE", "%$keyword%");
        }

        if ($filter = $filters['filter']) {
            if ($filter == "admin")
                $query->whereHas('role', function ($query) use ($keyword) {
                $query->where("role_id", 1);
            });
            else
                $query->whereHas('role', function ($query) use ($keyword) {
                $query->where("role_id", 2);
            });
        }

        if ($order = $filters['order']) {
            $query->orderBy('created_at', $order);
        } else {
            $query->orderBy('created_at', 'desc');
        }
    }

    /**
     * @param $query
     */
    public function scopeUserRole($query)
    {
        $query->whereHas('role', function ($query) {
            $query->where("role_id", 2);
        });
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Http\Requests\UserRequest;
use App\Mail\UserPasswordCreated;
use Illuminate\Support\Facades\Mail;
use App\UserRole;

class UserController extends Controller
{
     /**
     * @var User
     */
    protected $oUser;

    /**
     * UserController constructor.
     * @param User $oUser
     */
    public function __construct(User $oUser)
    {
        $this->middleware('auth');
        $this->middleware('admin');

        $this->oUser = $oUser;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $oUsers = $this->oUser
            ->where('id', '!=', auth()->id())
            ->filter(request()->all(['search', 'filter', 'order']))
            ->paginate(10);

        return view('user.index', compact('oUsers'));
    }

      /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.create', ['oUser' => isset($oUser) ? $oUser : []]);
    }

     /**
     * @param UserRequest $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(UserRequest $request)
    {
        $sPassword = substr(md5(microtime()),rand(0,26),6);
        $oUser = $this->oUser->create(array_merge($request->all(), ['password' => bcrypt($sPassword)]));
        $oUser->saveUserRole(new UserRole(), 2);

        Mail::to($oUser)->send(new UserPasswordCreated($sPassword));

        $request->session()->flash('message', __('Successfully created user with name'). ' ' . $oUser->name . '.');
        return redirect('/user');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Book  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('user.edit', ['oUser' => $user]);
    }

    /**
     * @param UserRequest $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(UserRequest $request, $id)
    {
        $oUser = $this->oUser->find($id);
        $oUser->update($request->all());

        $request->session()->flash('message', __('Successfully edited user with name') . ' ' . $oUser->name . '.');
        return redirect('/user');
    }

     /** 
     * @param Request $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy(Request $request, $id)
    {
        $this->oUser->destroy($id);

        $request->session()->flash('message', __('Successfully deleted user') . '.');
        return redirect('/user');
    }
}

resources/views/user/create.blade.php
@extends('layouts.app')

@section('content')

    <h2>{{ request()->has('copy') ? __('Copy a book') : __('Create a user') }}</h2>

    <form action="{{ route('user.store') }}" method="post">
        {{ csrf_field() }}  

        <div class="form-group required {{ $errors->has('name') ? 'has-error': '' }}">
            <label class="control-label" for="name">{{ __('Name') }}</label>
            <input id="name" type="text" name="name" class='form-control' value="{{ !empty($oBook) ? $oBook->name : old('name') }}">
            <div class="help-block">{{ $errors->first('name') }}</div>
        </div>

        <div class="form-group required {{ $errors->has('last_name') ? 'has-error': '' }}">
            <label class="control-label" for="last_name">{{ __('Last Name') }}</label>
            <input id="last_name" type="text" name="last_name" class='form-control' value="{{ !empty($oBook) ? $oBook->last_name : old('last_name') }}">
            <div class="help-block">{{ $errors->first('last_name') }}</div>
        </div>

        <div class="form-group required {{ $errors->has('email') ? 'has-error': '' }}">
            <label class="control-label" for="email">{{ __('Email') }}</label>
            <input id="email" type="email" name="email" class='form-control' value="{{ !empty($oBook) ? $oBook->email : old('email') }}">
            <div class="help-block">{{ $errors->first('email') }}</div>
        </div>

        <input type="submit" class='btn btn-primary' value="{{ __('Save') }}">
        <a href="{{ URL::previous() }}" class='btn btn-default'>{{ __('Back') }}</a>

    </form>
    &nbsp

@endsection

resources/views/user/edit.blade.php
@extends('layouts.app')

@section('content')

    <h2>{{ __('Update a user') }}</h2>

    <form action="{{ route('user.update', $oUser->id) }}" method="post">
        <input name="_method" type="hidden" value="PUT">
        {{ csrf_field() }}

        <div class="form-group required {{ $errors->has('name') ? 'has-error': '' }}">
            <label class="control-label" for="name">{{ __('Name') }}</label>
            <input id="name" type="text" name="name" class='form-control' value="{{ isset($oUser) ? $oUser->name : old('name') }}">
            <div class="help-block">{{ $errors->first('name') }}</div>
        </div>

        <div class="form-group required {{ $errors->has('last_name') ? 'has-error': '' }}">
            <label class="control-label" for="last_name">{{ __('Last Name') }}</label>
            <input id="last_name" type="text" name="last_name" class='form-control' value="{{ isset($oUser) ? $oUser->last_name : old('last_name') }}">
            <div class="help-block">{{ $errors->first('last_name') }}</div>
        </div>

        <div class="form-group required {{ $errors->has('email') ? 'has-error': '' }}">
            <label class="control-label" for="email">{{ __('Email') }}</label>
            <input id="email" type="text" name="email" class='form-control' value="{{ isset($oUser) ? $oUser->email : old('email') }}">
            <div class="help-block">{{ $errors->first('email') }}</div>
        </div>

        <input type="submit" class='btn btn-primary' value="{{ __('Save') }}">
        <a href="{{ URL::previous() }}" class='btn btn-default'>{{ __('Back') }}</a>

    </form>
    &nbsp

@endsection

resources/views/user/index.blade.php
@extends('layouts.app')

@section('content')

    @include('layouts.message')

    <h3>{{ __('Users') }}</h3>

    <a href="/user/create" class="btn btn-default" style="margin-bottom:15px;">
        <span class="glyphicon glyphicon-plus"></span>
        {{ __('Create a user') }}
    </a>
    
    <div class="row text-center">
        <form action="{{ url('/user') }}" method="get">
            <div class="col-md-5 form-group">
                <div class="input-group col-md-12">
                    <input type="text" name="search" value="{{ request('search') }}" class="form-control" placeholder="{{ __('Search by name') }}"/>
                    <input type="hidden" name="order" value="{{ request('order') }}"/>
                    <input type="hidden" name="filter" value="{{ request('filter') }}"/>
                    <span class="input-group-btn">
                        <button class="btn btn-primary" type="submit">
                            {{ __('Search') }}
                        </button>
                    </span>
                </div>
            </div>
        </form>
        @include('layouts.search', ['filter' => ['admin', 'user']])
    </div>

    @if(count($oUsers))

        <div class="table-responsive">
            <table class="table" data-form="deleteForm">
                <thead class="thead-inverse">
                <tr>
                    <th>{{ __('Name') }}</th>
                    <th>{{ __('Last Name') }}</th>
                    <th>{{ __('Email') }}</th>
                    <th>{{ __('Role') }}</th>
                    <th>{{ __('Added') }}</th>
                    <th style="width:10%">{{ __('Action') }}</th>
                </tr>
                </thead>
                <tbody>
                @foreach($oUsers as $oUser)
                    <tr>
                        <td>{{ isset($oUser->name) ? str_limit($oUser->name, 20, '...') : '' }}</td>
                        <td>{{ isset($oUser->last_name) ? str_limit($oUser->last_name, 20, '...') : '' }}</td>
                        <td>{{ isset($oUser->email) ? str_limit($oUser->email, 20, '...' ): '' }}</td>
                        <td>{{ $oUser->role && $oUser->role->role_id == 1 ? str_limit(__(ucfirst('Admin'))) : str_limit(__(ucfirst('User'))) }}</td>
                        <td>{{ isset($oUser->created_at) ? $oUser->created_at->format('d-m-Y') : '' }}</td>
                        
                        <td>
                            <div style="width:max-content;">     
                                <a href="/user/{{$oUser->id}}/edit" class="btn btn-primary pull-left form-group" style="margin-right: 5px;">
                                    <span class="glyphicon glyphicon-pencil"></span>
                                </a>
                                
                                {{ Form::model($oUser, ['method' => 'delete', 'route' => ['user.destroy', $oUser->id], 'class' => 'pull-right form-delete']) }}
                                {{ Form::hidden('id', $oUser->id) }}
                                {{ Form::button('<span class="glyphicon glyphicon-remove"></span>', ['type' => 'submit', 'class' => 'btn btn-danger'] )  }}
                                {{ Form::close() }}

                            </div>
                        </td>

                    </tr>
                @endforeach
                </tbody>
            </table>

            @include('modals.delete-modal')
        </div>

        {{ $oUsers->appends(['order' => request('order'), 'filter' => request('filter')])->links() }}

    @else

        <div class="alert alert-warning">
            {{ __('No users found') }}.
        </div>

    @endif
@endsection